# Generated by Django 6.0.5 on 2026-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(unique=True)),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.FloatField()),
                ('eemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
